services:
  app:
    build: .
    env_file: .env
    environment:
      - HTTPS_PROXY=${HTTPS_PROXY}
      - HTTP_PROXY=${HTTP_PROXY}
      - ALL_PROXY=${ALL_PROXY}
      - NO_PROXY=localhost,127.0.0.1,193320.voice.plusofon.ru
    ports:
      - "5060:5060/udp"
      - "10000-10100:10000-10100/udp"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
